<?php

// Create our custom group and fields
return array(
  0 => array(		
    'entity' => 'CustomGroup',
    'name' => 'Voter_Info',
    'update' => 'never',
    'params' => array(
      'version' => 3,
      'is_active' => 1,
      'name' => 'Voter_Info',
      'title' => 'Voter Info',
      'extends' => 'Individual',
      'style' => 'Tab',
      'collapse_display' => '1',
      'weight' => '23',
      'is_active' => '1',
      'is_multiple' => '0',
      'collapse_adv_display' => '1',
      'is_reserved' => '0',
      'is_public' => '1',
      'api.custom_field.create' => array(
       array(
          'custom_group_id' => '$value.id',
          'name' => 'voterfields_party_registration',
          'label' => 'Party Registration',
          'data_type' => 'String',
          'html_type' => 'Radio',
          'is_required' => '0',
          'is_searchable' => '1',
          'is_search_range' => '0',
          'weight' => '10',
          'is_active' => '1',
          'is_view' => '0',
          'text_length' => '255',
          'note_columns' => '60',
          'note_rows' => '4',
          'in_selector' => '0',
        ),
        array(
          'custom_group_id' => '$value.id',
          'name' => 'voterfields_if_other_party',
          'label' => 'If other party...',
          'data_type' => 'String',
          'html_type' => 'Text',
          'is_required' => '0',
          'is_searchable' => '1',
          'is_search_range' => '0',
          'weight' => '20',
          'is_active' => '1',
          'is_view' => '0',
          'text_length' => '255',
          'note_columns' => '60',
          'note_rows' => '4',
          'in_selector' => '0'
        ),
        array(
          'custom_group_id' => '$value.id',
          'name' => 'voterfields_voter_registration_date',
          'label' => 'Voter Registration Date',
          'data_type' => 'Date',
          'html_type' => 'Select Date',
          'is_required' => '0',
          'is_searchable' => '1',
          'is_search_range' => '1',
          'weight' => '30',
          'is_active' => '1',
          'is_view' => '0',
          'text_length' => '255',
          'date_format' => 'mm/dd/yy',
          'note_columns' => '60',
          'note_rows' => '4',
          'in_selector' => '0'
        ),
        array(
          'custom_group_id' => '$value.id',
          'name' => 'voterfields_state_voter_id',
          'label' => 'State Voter ID',
          'data_type' => 'Float',
          'html_type' => 'Text',
          'is_required' => '0',
          'is_searchable' => '1',
          'is_search_range' => '1',
          'weight' => '40',
          'is_active' => '1',
          'is_view' => '0',
          'text_length' => '255',
          'note_columns' => '60',
          'note_rows' => '4',
          'in_selector' => '0'
        ),
         array(
          'custom_group_id' => '$value.id',
          'name' => 'voterfields_van_id',
          'label' => 'Van ID',
          'data_type' => 'String',
          'html_type' => 'Text',
          'is_required' => '0',
          'is_searchable' => '1',
          'is_search_range' => '0',
          'weight' => '50',
          'is_active' => '1',
          'is_view' => '0',
          'text_length' => '255',
          'note_columns' => '60',
          'note_rows' => '4',
          'in_selector' => '0'
        ),
        array(
          'custom_group_id' => '$value.id',
          'name' => 'voterfields_congressional_district',
          'label' => 'Congressional District',
          'data_type' => 'String',
          'html_type' => 'Text',
          'is_required' => '0',
          'is_searchable' => '1',
          'is_search_range' => '0',
          'weight' => '60',
          'is_active' => '1',
          'is_view' => '0',
          'text_length' => '255',
          'date_format' => 'Array',
          'note_columns' => '60',
          'note_rows' => '4',
          'in_selector' => '0'
        ),
        array(
          'custom_group_id' => '$value.id',
          'name' => 'voterfields_state_senate_district',
          'label' => 'State Senate District',
          'data_type' => 'String',
          'html_type' => 'Text',
          'is_required' => '0',
          'is_searchable' => '1',
          'is_search_range' => '0',
          'weight' => '70',
          'is_active' => '1',
          'is_view' => '0',
          'text_length' => '255',
          'note_columns' => '60',
          'note_rows' => '4',
          'in_selector' => '0'
        ),
        array(
          'custom_group_id' => '$value.id',
          'name' => 'voterfields_state_assembly_district',
          'label' => 'State Assembly District',
          'data_type' => 'String',
          'html_type' => 'Text',
          'is_required' => '0',
          'is_searchable' => '1',
          'is_search_range' => '0',
          'weight' => '80',
          'is_active' => '1',
          'is_view' => '0',
          'text_length' => '255',
          'note_columns' => '60',
          'note_rows' => '4',
          'in_selector' => '0'
        ),
        array(
          'custom_group_id' => '$value.id',
          'name' => 'voterfields_county_file_id',
          'label' => 'County File ID',
          'data_type' => 'String',
          'html_type' => 'Text',
          'is_required' => '0',
          'is_searchable' => '0',
          'is_search_range' => '0',
          'weight' => '90',
          'is_active' => '1',
          'is_view' => '0',
          'text_length' => '255',
          'note_columns' => '60',
          'note_rows' => '4',
          'in_selector' => '0'
        ),
        array(
          'custom_group_id' => '$value.id',
          'name' => 'voterfields_county_district',
          'label' => 'County District',
          'data_type' => 'String',
          'html_type' => 'Text',
          'is_required' => '0',
          'is_searchable' => '1',
          'is_search_range' => '0',
          'weight' => '100',
          'is_active' => '1',
          'is_view' => '0',
          'text_length' => '255',
          'note_columns' => '60',
          'note_rows' => '4',
          'in_selector' => '0'
        ),
        array(
          'custom_group_id' => '$value.id',
          'name' => 'voterfields_precinct',
          'label' => 'Precinct',
          'data_type' => 'String',
          'html_type' => 'Text',
          'is_required' => '0',
          'is_searchable' => '1',
          'is_search_range' => '0',
          'weight' => '110',
          'is_active' => '1',
          'is_view' => '0',
          'text_length' => '255',
          'note_columns' => '60',
          'note_rows' => '4',
          'in_selector' => '0'
        ),
        array(
          'custom_group_id' => '$value.id',
          'name' => 'voterfields_city_district',
          'label' => 'City District',
          'data_type' => 'String',
          'html_type' => 'Text',
          'is_required' => '0',
          'is_searchable' => '1',
          'is_search_range' => '0',
          'weight' => '120',
          'is_active' => '1',
          'is_view' => '0',
          'text_length' => '255',
          'note_columns' => '60',
          'note_rows' => '4',
          'in_selector' => '0'
        ),
        array(
          'custom_group_id' => '$value.id',
          'name' => 'voterfields_school_district',
          'label' => 'School District',
          'data_type' => 'String',
          'html_type' => 'Text',
          'is_required' => '0',
          'is_searchable' => '1',
          'is_search_range' => '0',
          'weight' => '130',
          'is_active' => '1',
          'is_view' => '0',
          'text_length' => '255',
          'note_columns' => '60',
          'note_rows' => '4',
          'in_selector' => '0'
        ),
      )
    )
  ),
  1 => array(		
    'entity' => 'OptionGroup',
    'name' => 'voterfields_political_parties',
    'update' => 'never',
    'params' => array(
      'version' => 3,
      'is_active' => 1,
      'name' => 'voterfields_political_parties',
      'title' => 'Political Parties',
      'is_reserved' => '0',
      'is_active' => '1',
      'is_locked' => '0',
      'api.option_value.create' => array(
         array(
          'option_group_id' => '$value.id',
          'label' => 'Democrat',
          'value' => '1',
          'name' => 'democrat',
          'filter' => '0',
          'is_default' => '0',
          'weight' => '1',
          'is_optgroup' => '0',
          'is_reserved' => '0',
          'is_active' => '1'
        ),
        array(
          'option_group_id' => '$value.id',
          'label' => 'Republican',
          'value' => '2',
          'name' => 'republican',
          'filter' => '0',
          'is_default' => '0',
          'weight' => '2',
          'is_optgroup' => '0',
          'is_reserved' => '0',
          'is_active' => '1'
         ),
         array(
          'option_group_id' => '$value.id',
          'label' => 'Green',
          'value' => '3',
          'name' => 'green',
          'filter' => '0',
          'is_default' => '0',
          'weight' => '3',
          'is_optgroup' => '0',
          'is_reserved' => '0',
          'is_active' => '1'
         ),
         array(
          'option_group_id' => '$value.id',
          'label' => 'Independent',
          'value' => '4',
          'name' => 'independent',
          'filter' => '0',
          'is_default' => '0',
          'weight' => '4',
          'is_optgroup' => '0',
          'is_reserved' => '0',
          'is_active' => '1'
         ),
         array(
          'option_group_id' => '$value.id',
          'label' => 'Libertarian',
          'value' => '5',
          'name' => 'libertarian',
          'filter' => '0',
          'is_default' => '0',
          'weight' => '5',
          'is_optgroup' => '0',
          'is_reserved' => '0',
          'is_active' => '1'
         ),
         array(
          'option_group_id' => '$value.id',
          'label' => 'Undeclared',
          'value' => '6',
          'name' => 'undeclared',
          'filter' => '0',
          'is_default' => '0',
          'weight' => '6',
          'is_optgroup' => '0',
          'is_reserved' => '0',
          'is_active' => '1'
        ),
        array(
          'option_group_id' => '$value.id',
          'label' => 'Other',
          'name' => 'other',
          'value' => '7',
          'is_default' => '0',
          'weight' => '7',
          'is_optgroup' => '0',
          'is_reserved' => '0',
          'is_active' => '1'
         )
      )
    )
  )
);
